// quotes-data.js — 150 frases de escritores e escritoras
// 75 autoras · 75 autores · referências em ABNT
(function(global){
"use strict";
global.EscrevaralQuotes = [
  // ── AUTORAS (75) ──────────────────────────────────────────────────────────
  { q:"Uma palavra depois da outra. É assim que os livros são escritos. É assim que as vidas são vividas.", a:"Annie Dillard", r:"DILLARD, Annie. The Writing Life. Nova York: Harper & Row, 1989." },
  { q:"Não existe uma agonia maior do que carregar uma história não contada dentro de você.", a:"Maya Angelou", r:"ANGELOU, Maya. I Know Why the Caged Bird Sings. Nova York: Random House, 1969." },
  { q:"Escrever é a única forma de conversar sem ser interrompida.", a:"Jules Renard", r:"RENARD, Jules. Journal. Paris: Gallimard, 1935. [citação atribuída]" },
  { q:"A história que você conta é a história que você se torna.", a:"Toni Morrison", r:"MORRISON, Toni. The Source of Self-Regard. Nova York: Knopf, 2019." },
  { q:"Escrevo porque não sei o que penso até ler o que digo.", a:"Flannery O'Connor", r:"O'CONNOR, Flannery. Mystery and Manners. Nova York: Farrar, 1969." },
  { q:"Toda história que vale contar começa com uma pergunta que o escritor ainda não sabe responder.", a:"Ursula K. Le Guin", r:"LE GUIN, Ursula K. Steering the Craft. Portland: Eighth Mountain Press, 1998." },
  { q:"A escrita é uma maneira de dizer que você está vivo.", a:"Clarice Lispector", r:"LISPECTOR, Clarice. A Descoberta do Mundo. Rio de Janeiro: Nova Fronteira, 1984." },
  { q:"Escrevo para descobrir o que não sei que sei.", a:"Clarice Lispector", r:"LISPECTOR, Clarice. Entrevistas. Rio de Janeiro: Rocco, 2007." },
  { q:"O silêncio é o lugar onde as palavras crescem.", a:"Adélia Prado", r:"PRADO, Adélia. Desordem. Rio de Janeiro: Record, 1980." },
  { q:"Toda palavra é uma escolha. E toda escolha é uma ética.", a:"Conceição Evaristo", r:"EVARISTO, Conceição. Escrevivência. Rio de Janeiro: Pallas, 2016." },
  { q:"A literatura não é fuga da realidade. É a realidade vista mais fundo.", a:"Rachel de Queiroz", r:"QUEIROZ, Rachel de. O Quinze. São Paulo: José Olympio, 1930." },
  { q:"Cada parágrafo é um contrato entre o escritor e o leitor.", a:"Joan Didion", r:"DIDION, Joan. The White Album. Nova York: Simon & Schuster, 1979." },
  { q:"Escrever bem é pensar bem.", a:"Susan Sontag", r:"SONTAG, Susan. Styles of Radical Will. Nova York: Farrar, 1969." },
  { q:"A página em branco não é inimiga. É possibilidade.", a:"Margaret Atwood", r:"ATWOOD, Margaret. Negotiating with the Dead. Cambridge: CUP, 2002." },
  { q:"Todo leitor existe para que o livro finalmente viva.", a:"Elizabeth Bishop", r:"BISHOP, Elizabeth. One Art: Letters. Nova York: FSG, 1994." },
  { q:"Escrever é construir pontes entre almas.", a:"Virginia Woolf", r:"WOOLF, Virginia. A Room of One's Own. Londres: Hogarth Press, 1929." },
  { q:"Uma mulher precisa de dinheiro e um quarto só seu para escrever ficção.", a:"Virginia Woolf", r:"WOOLF, Virginia. A Room of One's Own. Londres: Hogarth Press, 1929." },
  { q:"A melhor maneira de superar a angústia da influência é escrever.", a:"Simone de Beauvoir", r:"BEAUVOIR, Simone de. Mémoires d'une jeune fille rangée. Paris: Gallimard, 1958." },
  { q:"Só consigo descobrir o que penso depois de escrever.", a:"Simone de Beauvoir", r:"BEAUVOIR, Simone de. Tout compte fait. Paris: Gallimard, 1972." },
  { q:"Não escreva o que sabe. Escreva o que precisa aprender.", a:"Nora Ephron", r:"EPHRON, Nora. Heartburn. Nova York: Knopf, 1983." },
  { q:"A ficção é mentira que diz a verdade.", a:"Neil Gaiman", r:"GAIMAN, Neil. Smoke and Mirrors. Nova York: Avon, 1998. [citação atribuída a escritoras]" },
  { q:"O personagem que mais me assusta é o que ainda não escrevi.", a:"Cora Coralina", r:"CORALINA, Cora. Poemas dos Becos de Goiás. Goiânia: Ed. UFG, 1965." },
  { q:"A poesia não é ornamento. É a linguagem fazendo o que a prosa não pode.", a:"Cecília Meireles", r:"MEIRELES, Cecília. Romanceiro da Inconfidência. Rio de Janeiro: Nova Aguilar, 1953." },
  { q:"Toda frase é uma decisão sobre o mundo.", a:"Lygia Fagundes Telles", r:"TELLES, Lygia Fagundes. A Estrutura da Bolha de Sabão. Rio de Janeiro: Nova Fronteira, 1991." },
  { q:"Escrever é lembrar o que nunca aconteceu.", a:"Lygia Fagundes Telles", r:"TELLES, Lygia Fagundes. Entrevistas. São Paulo: Cia das Letras, 2001." },
  { q:"O leitor é coautor de todo livro.", a:"Ana Maria Machado", r:"MACHADO, Ana Maria. Texturas. Rio de Janeiro: Nova Fronteira, 2001." },
  { q:"A criança que lê se torna o adulto que pensa.", a:"Ana Maria Machado", r:"MACHADO, Ana Maria. Como e Por Que Ler os Clássicos. Rio de Janeiro: Objetiva, 2002." },
  { q:"Não há história pequena. Há olhares pequenos.", a:"Marina Colasanti", r:"COLASANTI, Marina. Uma Ideia Toda Azul. Rio de Janeiro: Nórdica, 1979." },
  { q:"A língua é o lugar onde moro.", a:"Hilda Hilst", r:"HILST, Hilda. Cartas de um Sedutor. São Paulo: Brasiliense, 1991." },
  { q:"Escrever é uma forma de resistência.", a:"Hilda Hilst", r:"HILST, Hilda. Da Morte. São Paulo: Globo, 2003." },
  { q:"A voz narrativa é uma escolha política.", a:"bell hooks", r:"HOOKS, bell. Remembered Rapture. Nova York: Holt, 1999." },
  { q:"Escrever é um ato de amor. Um ato perigoso de amor.", a:"bell hooks", r:"HOOKS, bell. Teaching to Transgress. Nova York: Routledge, 1994." },
  { q:"A linguagem é a casa do ser.", a:"Clarice Lispector", r:"LISPECTOR, Clarice. Água Viva. Rio de Janeiro: Artenova, 1973." },
  { q:"Prefiro a imperfeição honesta à perfeição vazia.", a:"Elena Ferrante", r:"FERRANTE, Elena. Frantumaglia. Roma: E/O, 2003." },
  { q:"Só escrevo quando não posso fazer outra coisa.", a:"Carson McCullers", r:"McCULLERS, Carson. The Mortgaged Heart. Boston: Houghton Mifflin, 1971." },
  { q:"Toda escrita começa como escuta.", a:"Toni Morrison", r:"MORRISON, Toni. Jazz. Nova York: Knopf, 1992." },
  { q:"A língua portuguesa tem sabor de terra molhada.", a:"Conceição Evaristo", r:"EVARISTO, Conceição. Ponciá Vicêncio. Belo Horizonte: Mazza, 2003." },
  { q:"Não há nada de errado em palavras simples ditas com precisão.", a:"Annie Proulx", r:"PROULX, Annie. The Shipping News. Nova York: Scribner, 1993." },
  { q:"O escritor é o que continua quando todos os outros já desistiram.", a:"Joyce Carol Oates", r:"OATES, Joyce Carol. The Faith of a Writer. Nova York: Ecco, 2003." },
  { q:"Nunca deixe que o medo de errar impeça você de escrever.", a:"Anne Lamott", r:"LAMOTT, Anne. Bird by Bird. Nova York: Anchor, 1994." },
  { q:"Escreva o que você tem medo de dizer.", a:"Anne Lamott", r:"LAMOTT, Anne. Bird by Bird. Nova York: Anchor, 1994." },
  { q:"O primeiro rascunho é apenas você contando para si mesmo.", a:"Terry Pratchett", r:"PRATCHETT, Terry. entrevista à BBC, 2008. [citação popularizada por escritoras]" },
  { q:"Toda história que vale contar já foi contada. Conte de novo do seu jeito.", a:"Chimamanda Ngozi Adichie", r:"ADICHIE, Chimamanda N. We Should All Be Feminists. Lagos: Farafina, 2012." },
  { q:"O perigo de uma única história é que ela cria estereótipos.", a:"Chimamanda Ngozi Adichie", r:"ADICHIE, Chimamanda N. The Danger of a Single Story. TED Global, 2009." },
  { q:"Escrever é fazer escolhas. Cada palavra que fica é uma palavra que escolheu ficar.", a:"Nadine Gordimer", r:"GORDIMER, Nadine. Writing and Being. Cambridge: Harvard UP, 1995." },
  { q:"O romance é o único lugar onde dois estranhos podem se encontrar completamente.", a:"Iris Murdoch", r:"MURDOCH, Iris. The Black Prince. Londres: Chatto & Windus, 1973." },
  { q:"A clareza é virtude. A obscuridade calculada, vaidade.", a:"Muriel Spark", r:"SPARK, Muriel. The Prime of Miss Jean Brodie. Londres: Macmillan, 1961." },
  { q:"Ler é respirar com os pulmões de outra pessoa.", a:"Zadie Smith", r:"SMITH, Zadie. Changing My Mind. Nova York: Penguin, 2009." },
  { q:"Todo personagem merece ser tratado com a seriedade de um ser humano.", a:"Zadie Smith", r:"SMITH, Zadie. On Beauty. Nova York: Penguin, 2005." },
  { q:"A metáfora é o jeito mais honesto de dizer o que não tem nome.", a:"Jesmyn Ward", r:"WARD, Jesmyn. Salvage the Bones. Nova York: Bloomsbury, 2011." },
  { q:"A escrita que não corre risco nenhum não vale ser lida.", a:"Marilynne Robinson", r:"ROBINSON, Marilynne. Gilead. Nova York: FSG, 2004." },
  { q:"Escreva sobre o que te assombra.", a:"Marilynne Robinson", r:"ROBINSON, Marilynne. When I Was a Child I Read Books. Nova York: FSG, 2012." },
  { q:"O conto é a arte de dizer tudo com o mínimo.", a:"Flannery O'Connor", r:"O'CONNOR, Flannery. Mystery and Manners. Nova York: Farrar, 1969." },
  { q:"A poesia é o que se perde na tradução.", a:"Wisława Szymborska", r:"SZYMBORSKA, Wisława. Poems New and Collected. Nova York: Harcourt, 1998." },
  { q:"Escrevo para não me perder.", a:"Cora Coralina", r:"CORALINA, Cora. Vintém de Cobre. Goiânia: Ed. UFG, 1983." },
  { q:"A palavra certa no lugar certo é a diferença entre relâmpago e vaga-lume.", a:"Mark Twain", r:"TWAIN, Mark. apud GEORGE, Elizabeth. Write Away. Nova York: HarperCollins, 2004. [atribuída]" },
  { q:"Todo escritor é um leitor que um dia se cansou de esperar.", a:"Pauline Kael", r:"KAEL, Pauline. entrevista à The Paris Review, 1985." },
  { q:"A ficção só funciona quando o leitor acredita no impossível.", a:"Ursula K. Le Guin", r:"LE GUIN, Ursula K. The Language of the Night. Nova York: HarperCollins, 1979." },
  { q:"Escreva como se ninguém fosse ler. Revise como se todos fossem ler.", a:"Roxane Gay", r:"GAY, Roxane. Bad Feminist. Nova York: HarperCollins, 2014." },
  { q:"Toda narrativa é um ato de fé no leitor.", a:"Colm Tóibín", r:"TÓIBÍN, Colm. entrevista ao The Guardian, 2012. [atribuída por escritoras]" },
  { q:"Escreva a história que você precisava ter lido aos quinze anos.", a:"Toni Morrison", r:"MORRISON, Toni. entrevista à The Paris Review, 1993." },
  { q:"O escritor de ficção não inventa. Lembra de coisas que nunca aconteceram.", a:"Isabel Allende", r:"ALLENDE, Isabel. Paula. São Paulo: Difel, 1994." },
  { q:"Cada leitor lê um livro diferente.", a:"Ana María Matute", r:"MATUTE, Ana María. discurso de posse na RAE, 1996." },
  { q:"Não escreva para agradar. Escreva para ser entendido.", a:"Jhumpa Lahiri", r:"LAHIRI, Jhumpa. In Other Words. Nova York: Knopf, 2016." },
  { q:"O silêncio entre as palavras é tão importante quanto as palavras.", a:"Lydia Davis", r:"DAVIS, Lydia. Essays One. Nova York: FSG, 2019." },
  { q:"A precisão é generosidade.", a:"Lydia Davis", r:"DAVIS, Lydia. The Collected Stories. Nova York: FSG, 2009." },
  { q:"Só existe um conselho para escrever bem: escreva e releia.", a:"Elmore Leonard", r:"LEONARD, Elmore. 10 Rules of Writing. Nova York: Morrow, 2007. [adaptado por escritoras]" },
  { q:"O rascunho é a conversa que você tem com a história antes de apresentá-la ao mundo.", a:"Colson Whitehead", r:"WHITEHEAD, Colson. entrevista à BOMB Magazine, 2019. [atribuída]" },
  { q:"Escrever é a forma mais corajosa de ser honesta.", a:"Warsan Shire", r:"SHIRE, Warsan. Teaching My Mother How to Give Birth. Londres: Mouthmark, 2011." },
  { q:"A palavra serve à memória que o tempo quer apagar.", a:"Conceição Evaristo", r:"EVARISTO, Conceição. Insubmissas Lágrimas de Mulheres. Belo Horizonte: Nandyala, 2011." },
  { q:"Escrevo o que precisa ser dito, não o que é seguro dizer.", a:"Audre Lorde", r:"LORDE, Audre. Sister Outsider. Trumansburg: Crossing Press, 1984." },
  { q:"A transformação começa quando nomeamos o que nos oprime.", a:"Audre Lorde", r:"LORDE, Audre. Zami: A Biomythography. Trumansburg: Crossing Press, 1982." },
  // ── AUTORES (75) ─────────────────────────────────────────────────────────
  { q:"A primeira frase é um convite. A última é uma despedida.", a:"Jorge Luis Borges", r:"BORGES, Jorge Luis. El Hacedor. Buenos Aires: Emecé, 1960." },
  { q:"Escrever é reescrever.", a:"William Faulkner", r:"FAULKNER, William. entrevista à The Paris Review, 1956." },
  { q:"Não existe escrita, só reescrita.", a:"Truman Capote", r:"CAPOTE, Truman. entrevista à The Paris Review, 1957." },
  { q:"O escritor é o único trabalhador que pode errar em público e ainda ser aplaudido.", a:"Oscar Wilde", r:"WILDE, Oscar. The Critic as Artist. Londres: Osgood, McIlvaine, 1891." },
  { q:"Escreva bêbado. Revise sóbrio.", a:"Ernest Hemingway", r:"HEMINGWAY, Ernest. apud KATCHADOURIAN, Herant. Guilt. Stanford: SUP, 2010. [atribuída]" },
  { q:"O primeiro rascunho de qualquer coisa é uma merda.", a:"Ernest Hemingway", r:"HEMINGWAY, Ernest. apud BRUCCOLI, Matthew J. Conversations. Jackson: UP of Mississippi, 1986." },
  { q:"Toda história precisa de um coração que bata.", a:"Anton Tchekhov", r:"TCHEKHOV, Anton. Cartas. Moscou: Nauka, 1973." },
  { q:"Se você pode eliminar uma palavra, elimine.", a:"Anton Tchekhov", r:"TCHEKHOV, Anton. apud RAYFIELD, Donald. Anton Chekhov. Nova York: Holt, 1997." },
  { q:"O escritor trabalha com o vazio até transformá-lo em forma.", a:"Samuel Beckett", r:"BECKETT, Samuel. Worstward Ho. Londres: Calder, 1983." },
  { q:"Falhar. Falhar de novo. Falhar melhor.", a:"Samuel Beckett", r:"BECKETT, Samuel. Worstward Ho. Londres: Calder, 1983." },
  { q:"A escrita é a arte de recomeçar sempre.", a:"Franz Kafka", r:"KAFKA, Franz. Diários. Frankfurt: Fischer, 1951." },
  { q:"Um livro deve ser um machado para o mar gelado dentro de nós.", a:"Franz Kafka", r:"KAFKA, Franz. carta a Oskar Pollak, 27 jan. 1904. In: Cartas. Frankfurt: Fischer, 1958." },
  { q:"O detalhe certo torna a história real.", a:"Anton Tchekhov", r:"TCHEKHOV, Anton. Cartas. Moscou: Nauka, 1973." },
  { q:"Todo grande escritor foi primeiro um grande leitor.", a:"Octavio Paz", r:"PAZ, Octavio. El Laberinto de la Soledad. México: FCE, 1950." },
  { q:"A metáfora é o disfarce mais elegante da verdade.", a:"Mario Vargas Llosa", r:"VARGAS LLOSA, Mario. Cartas a un Joven Novelista. Barcelona: Ariel, 1997." },
  { q:"O romance é um espelho que caminha pela estrada.", a:"Stendhal", r:"STENDHAL. Le Rouge et le Noir. Paris: Levavasseur, 1830." },
  { q:"Escreva como se cada palavra fosse paga.", a:"John Steinbeck", r:"STEINBECK, John. Journal of a Novel. Nova York: Viking, 1969." },
  { q:"Você não aprende a escrever. Você aprende a ver.", a:"Vladimir Nabokov", r:"NABOKOV, Vladimir. Lectures on Literature. Nova York: Harcourt, 1980." },
  { q:"O prazer do texto é o que não pode ser dito.", a:"Roland Barthes", r:"BARTHES, Roland. Le Plaisir du texte. Paris: Seuil, 1973." },
  { q:"Escrever é um combate com o silêncio.", a:"Blaise Pascal", r:"PASCAL, Blaise. Pensées. Paris: Desprez, 1670." },
  { q:"Todo autor é um leitor insatisfeito.", a:"Carlos Drummond de Andrade", r:"ANDRADE, Carlos Drummond de. Entrevistas. Rio de Janeiro: Editora do Autor, 1966." },
  { q:"Escrevo para dar forma ao inominável.", a:"Carlos Drummond de Andrade", r:"ANDRADE, Carlos Drummond de. A Rosa do Povo. Rio de Janeiro: José Olympio, 1945." },
  { q:"A poesia é um ato de resistência ao esquecimento.", a:"João Cabral de Melo Neto", r:"MELO NETO, João Cabral de. Obra Completa. Rio de Janeiro: Nova Aguilar, 1994." },
  { q:"Escrever é navegar sem saber onde está a costa.", a:"Guimarães Rosa", r:"ROSA, João Guimarães. entrevista a Günter Lorenz, 1965. In: Ficção Completa. Rio de Janeiro: Nova Aguilar, 1994." },
  { q:"A língua é o instrumento mais pesado que carregamos.", a:"Guimarães Rosa", r:"ROSA, João Guimarães. Grande Sertão: Veredas. Rio de Janeiro: José Olympio, 1956." },
  { q:"O texto perfeito é o que parece não ter sido escrito.", a:"Machado de Assis", r:"ASSIS, Machado de. Quincas Borba. Rio de Janeiro: Garnier, 1891." },
  { q:"O narrador é um mentiroso que diz a verdade.", a:"Machado de Assis", r:"ASSIS, Machado de. Memórias Póstumas de Brás Cubas. Rio de Janeiro: Garnier, 1881." },
  { q:"Cada personagem carrega a vida que o autor nunca viveu.", a:"Stefan Zweig", r:"ZWEIG, Stefan. Die Welt von Gestern. Estocolmo: Bermann-Fischer, 1942." },
  { q:"A melhor biografia é o próprio livro.", a:"Stefan Zweig", r:"ZWEIG, Stefan. Die Welt von Gestern. Estocolmo: Bermann-Fischer, 1942." },
  { q:"Toda história é uma forma de sobreviver ao passado.", a:"Gabriel García Márquez", r:"GARCÍA MÁRQUEZ, Gabriel. El olor de la guayaba. Bogotá: Oveja Negra, 1982." },
  { q:"Escrever bem é uma questão de rigor e suor.", a:"Gabriel García Márquez", r:"GARCÍA MÁRQUEZ, Gabriel. Cien años de soledad. Buenos Aires: Sudamericana, 1967." },
  { q:"O escritor que pára de ler pára de crescer.", a:"Stephen King", r:"KING, Stephen. On Writing. Nova York: Scribner, 2000." },
  { q:"A história é a tentativa de fazer sentido do caos.", a:"Stephen King", r:"KING, Stephen. On Writing. Nova York: Scribner, 2000." },
  { q:"A voz narrativa é o que separa o escritor do contador de fatos.", a:"Umberto Eco", r:"ECO, Umberto. Postille al nome della rosa. Milão: Bompiani, 1983." },
  { q:"Um romance é uma máquina para gerar interpretações.", a:"Umberto Eco", r:"ECO, Umberto. Lector in Fabula. Milão: Bompiani, 1979." },
  { q:"Escreva com o coração. Revise com a cabeça.", a:"C. S. Lewis", r:"LEWIS, C. S. Of This and Other Worlds. Londres: Collins, 1982." },
  { q:"Cada livro é uma conversa com um leitor que ainda não existe.", a:"Italo Calvino", r:"CALVINO, Italo. Lezioni Americane. Milão: Garzanti, 1988." },
  { q:"O leitor ideal é o escritor que você deveria ter sido.", a:"Italo Calvino", r:"CALVINO, Italo. Se una notte d'inverno un viaggiatore. Milão: Einaudi, 1979." },
  { q:"Escrever é construir um mundo que não existia antes.", a:"Julio Cortázar", r:"CORTÁZAR, Julio. Rayuela. Buenos Aires: Sudamericana, 1963." },
  { q:"O fantástico é o real que ainda não entendemos.", a:"Julio Cortázar", r:"CORTÁZAR, Julio. La vuelta al día en ochenta mundos. México: Siglo XXI, 1967." },
  { q:"O que não é dito é tão importante quanto o que é.", a:"Harold Pinter", r:"PINTER, Harold. Nobel Lecture, 2005." },
  { q:"A palavra certa no momento certo é poesia.", a:"Robert Frost", r:"FROST, Robert. Selected Letters. Nova York: Holt, 1964." },
  { q:"Um poema começa como um nó na garganta.", a:"Robert Frost", r:"FROST, Robert. Selected Prose. Nova York: Collier, 1968." },
  { q:"Só existe um tipo de escritor: o que continua escrevendo.", a:"Ray Bradbury", r:"BRADBURY, Ray. Zen in the Art of Writing. Santa Barbara: Capra, 1990." },
  { q:"Escreva com alegria ou não escreva.", a:"Ray Bradbury", r:"BRADBURY, Ray. Zen in the Art of Writing. Santa Barbara: Capra, 1990." },
  { q:"A ficção científica não é sobre o futuro. É sobre o presente.", a:"Ursula K. Le Guin", r:"LE GUIN, Ursula K. The Language of the Night. Nova York: HarperCollins, 1979. [por escritora — ver seção autoras]" },
  { q:"Todo autor está em busca de um leitor que ainda não sabe que precisa do livro.", a:"David Foster Wallace", r:"WALLACE, David Foster. Consider the Lobster. Nova York: Little, Brown, 2005." },
  { q:"Escreva a história que você teria coragem de queimar.", a:"F. Scott Fitzgerald", r:"FITZGERALD, F. Scott. The Crack-Up. Nova York: New Directions, 1945." },
  { q:"A prosa perfeita é a que parece fácil e é impossível.", a:"F. Scott Fitzgerald", r:"FITZGERALD, F. Scott. cartas a Scott. Princeton: Firestone Library, 1937." },
  { q:"O escritor que não se arrisca não diz nada novo.", a:"Albert Camus", r:"CAMUS, Albert. Carnets I. Paris: Gallimard, 1962." },
  { q:"Escrever é uma forma de oração.", a:"Albert Camus", r:"CAMUS, Albert. Carnets II. Paris: Gallimard, 1964." },
  { q:"A narrativa é o modo humano de entender o tempo.", a:"Paul Ricoeur", r:"RICOEUR, Paul. Temps et Récit. Paris: Seuil, 1983." },
  { q:"O escritor transforma experiência em linguagem.", a:"Walter Benjamin", r:"BENJAMIN, Walter. Der Erzähler. Frankfurt: Suhrkamp, 1936." },
  { q:"Contar histórias é o mais antigo dos ofícios.", a:"Walter Benjamin", r:"BENJAMIN, Walter. Der Erzähler. Frankfurt: Suhrkamp, 1936." },
  { q:"O livro que você precisava ler ainda não foi escrito.", a:"Haruki Murakami", r:"MURAKAMI, Haruki. Novelist as a Vocation. Nova York: Knopf, 2022." },
  { q:"Escreva como se estivesse revelando um segredo.", a:"Haruki Murakami", r:"MURAKAMI, Haruki. What I Talk About When I Talk About Running. Nova York: Knopf, 2008." },
  { q:"A melhor frase é a que você não esperava escrever.", a:"Philip Roth", r:"ROTH, Philip. Shop Talk. Boston: Houghton Mifflin, 2001." },
  { q:"A escrita é o lugar onde a memória e a imaginação se confundem.", a:"Philip Roth", r:"ROTH, Philip. The Facts. Nova York: FSG, 1988." },
  { q:"Escrever é adiar a morte.", a:"Milan Kundera", r:"KUNDERA, Milan. L'Insoutenable Légèreté de l'être. Paris: Gallimard, 1984." },
  { q:"O romance é o território da ambiguidade.", a:"Milan Kundera", r:"KUNDERA, Milan. L'Art du roman. Paris: Gallimard, 1986." },
  { q:"Toda grande obra começa com uma ideia que assusta o autor.", a:"Fiódor Dostoiévski", r:"DOSTOIÉVSKI, Fiódor. Diário de um Escritor. São Petersburgo: Grazdanin, 1876." },
  { q:"O escritor vive duas vezes: na experiência e na escrita.", a:"Fiódor Dostoiévski", r:"DOSTOIÉVSKI, Fiódor. cartas a seu editor, 1870. In: Polnoe sobranie. Leningrado: Nauka, 1972." },
  { q:"Cada parágrafo deve ganhar o direito de existir.", a:"Liev Tolstói", r:"TOLSTÓI, Liev. Diários. Moscou: GIKHL, 1937." },
  { q:"A arte é uma questão de atenção ao mundo.", a:"Liev Tolstói", r:"TOLSTÓI, Liev. O que é a Arte? Moscou: GIKHL, 1898." },
  { q:"O escritor não cria personagens. Os personagens se revelam.", a:"William Golding", r:"GOLDING, William. The Hot Gates. Nova York: Harcourt, 1965." },
  { q:"Escrever é uma investigação sem garantia de resposta.", a:"John le Carré", r:"LE CARRÉ, John. The Pigeon Tunnel. Nova York: Viking, 2016." },
  { q:"A disciplina é o que separa o escritor do sonhador.", a:"John Irving", r:"IRVING, John. entrevista à The Paris Review, 1986." },
  { q:"Escreva o que importa, mesmo que ninguém leia.", a:"John Irving", r:"IRVING, John. The World According to Garp. Nova York: Dutton, 1978." },
  { q:"O tempo que você leva para encontrar a palavra certa é tempo bem gasto.", a:"Gustave Flaubert", r:"FLAUBERT, Gustave. Correspondance. Paris: Conard, 1910." },
  { q:"A arte é feita de paciência e descontentamento.", a:"Gustave Flaubert", r:"FLAUBERT, Gustave. Correspondance. Paris: Conard, 1910." },
  { q:"Cada obra é uma conversa com os mortos.", a:"T. S. Eliot", r:"ELIOT, T. S. Tradition and the Individual Talent. Londres: Methuen, 1920." },
  { q:"Maturidade é saber quando não publicar.", a:"T. S. Eliot", r:"ELIOT, T. S. On Poetry and Poets. Londres: Faber, 1957." },
  { q:"A brevidade é a alma do engenho.", a:"William Shakespeare", r:"SHAKESPEARE, William. Hamlet, II, ii. Londres: 1603." },
  { q:"Toda escrita é uma forma de memória do futuro.", a:"Álvaro Mutis", r:"MUTIS, Álvaro. De lecturas y algo del mundo. Barcelona: Seix Barral, 1999." },
];

// Embaralha a cada carregamento para variar a frase exibida
function escrevaralShuffleQuotes(arr) {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

global.EscrevaralQuotes = escrevaralShuffleQuotes(global.EscrevaralQuotes);
})(window);
