const {chromium,webkit}=require('playwright'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..'),out=process.env.QA_OUTPUT||'/tmp',engine=process.env.BROWSER_ENGINE||'chromium';fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end(fs.readFileSync(path.join(root,'index.html')));});let browser;const errors=[];
async function create(p,name){await p.click('#project-new');await p.fill('#project-name',name);await p.click('#project-create');}
async function menu(p,id){await p.click('#os-start');await p.click(id);}
async function analyze(p){await p.click('#examinar-toggle');await p.click('[data-lens="ortografia"]');await p.waitForFunction(()=>!document.querySelector('[data-lens="ortografia"]').disabled);assert.ok(!(await p.locator('#analysis-status').textContent()).includes('Nenhuma análise iniciada'));}
async function current(p){return p.evaluate(()=>JSON.parse(localStorage.getItem('escrevaral.astra.v1.doc.'+localStorage.getItem('escrevaral.astra.current'))));}
async function shot(p,name){await p.screenshot({path:path.join(out,engine+'-'+name+'.png')});}
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;browser=await(engine==='webkit'?webkit:chromium).launch({headless:true,args:engine==='chromium'?['--no-sandbox']:[]});const c=await browser.newContext({viewport:{width:1366,height:768},serviceWorkers:'block',hasTouch:true}),p=await c.newPage();p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>{errors.push('native dialog');d.dismiss();});await p.goto(url);
 await create(p,'Era uma vez em Paris');assert.equal(await p.locator('#cabinet-context-label').textContent(),'CADERNO ABERTO · SUAS FOLHAS');assert.equal(await p.locator('#cabinet-window .project-shelf').isVisible(),false);assert.equal(await p.locator('.notebook-cover[aria-pressed="true"] .notebook-state').textContent(),'ABERTO');await shot(p,'caderno-aberto');
 await p.click('#notebook-back');assert.equal(await p.locator('.notebook-cover[aria-pressed="true"]').count(),0);await p.getByRole('button',{name:'Abrir caderno Era uma vez em Paris',exact:true}).click();
 for(const [w,h]of [[1366,768],[820,600],[390,844],[320,568],[667,375]]){
  await p.setViewportSize({width:w,height:h});for(const [trigger,panel]of [['#start-calculator','#utilidades'],['#start-calendar','#utilidades'],['#start-settings','#mesa']]){
   await menu(p,trigger);const b=await p.locator(panel).boundingBox();assert.ok(b.x>=0&&b.y>=0&&b.x+b.width<=w+1&&b.y+b.height<=h+1,JSON.stringify(b));assert.equal(await p.locator(panel).evaluate(n=>n.scrollWidth>n.clientWidth+1),false);
   if(trigger==='#start-calculator'){assert.ok(w<=760?b.width>=w-20:b.width<=350);await shot(p,'calculadora-'+w);await p.fill('#calculator-input','2+3*4');await p.locator('#calculator-input').press('Enter');assert.equal(await p.locator('#calculator-result').textContent(),'14');}
   await p.keyboard.press('Escape');
  }
 }
 await p.setViewportSize({width:1366,height:768});await p.click('#cabinet-new');await p.fill('#titulo','O cais');await p.fill('#manuscrito','agente vai ao cais.\nEle deixou o casaco.');await p.keyboard.press('Control+s');await menu(p,'#start-lineage');await p.click('#lineage-mark');await p.click('#lineage-close');
 const before=await p.locator('#manuscrito').inputValue();await p.fill('#manuscrito','agente vai ao cais.\nA tempestade tomou o casaco.');await p.keyboard.press('Control+s');await menu(p,'#start-lineage');assert.ok(await p.locator('#lineage-list button').count()>=2);await p.locator('#lineage-list button').first().click();assert.equal(await p.locator('#lineage-preview').inputValue(),before);await shot(p,'linhagem');await p.click('#lineage-restore');await p.click('#app-dialog-cancel');assert.notEqual(await p.locator('#manuscrito').inputValue(),before);await p.click('#lineage-restore');await p.click('#app-dialog-accept');assert.equal(await p.locator('#manuscrito').inputValue(),before);await p.click('#lineage-close');
 await analyze(p);assert.ok((await current(p)).linguistics.records.length);await p.keyboard.press('Escape');
 // IndexedDB contains versioned corpus and source-bound results.
 await p.waitForFunction(()=>new Promise(resolve=>{const r=indexedDB.open('escrevaral-linguistica',1);r.onsuccess=()=>{const db=r.result,t=db.transaction('cache','readonly'),s=t.objectStore('cache');let corpus=false,records=false;s.get('corpus').onsuccess=e=>corpus=!!e.target.result?.knowledge;s.get('recent').onsuccess=e=>records=!!e.target.result?.length;t.oncomplete=()=>{db.close();resolve(corpus&&records);};};r.onerror=()=>resolve(false);}));
 // Preserve history on reload, and recover analysis from IndexedDB without corpus reprocessing.
 await p.evaluate(()=>{const k='escrevaral.astra.v1.doc.'+localStorage.getItem('escrevaral.astra.current'),d=JSON.parse(localStorage.getItem(k));delete d.linguistics;localStorage.setItem(k,JSON.stringify(d));});await p.reload();if(await p.locator('#cabinet-resume').isVisible())await p.click('#cabinet-resume');await p.evaluate(()=>{Escr.analysisContract.analyze=function(){throw Error('Não deve reprocessar resultado persistido');};});await analyze(p);assert.ok(!(await p.locator('#analysis-status').textContent()).includes('Não deve reprocessar'));assert.ok((await current(p)).linguistics.records.length);await p.keyboard.press('Escape');
 // Full package includes lineage and writer's analyses.
 await p.click('#back-cabinet');let ev=p.waitForEvent('download');await p.click('#notebook-export');const packet=JSON.parse(fs.readFileSync(await(await ev).path(),'utf8'));assert.ok(packet.documents[0].lineage.entries.length);assert.ok(packet.documents[0].linguistics.records.length);
 const fallback=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});await fallback.addInitScript(()=>Object.defineProperty(window,'indexedDB',{value:{open(){throw Error('indisponível');}}}));const f=await fallback.newPage();f.on('pageerror',e=>errors.push(e.message));await f.goto(url);await create(f,'Legado');await f.click('#cabinet-new');await f.fill('#titulo','Folha');await f.fill('#manuscrito','Texto guardado sem banco de cache.');await analyze(f);assert.ok((await current(f)).linguistics.records.length);await f.reload();if(await f.locator('#cabinet-resume').isVisible())await f.click('#cabinet-resume');await analyze(f);assert.ok((await current(f)).linguistics.records.length);
 assert.deepEqual(errors,[]);console.log('OK '+engine+': estado do caderno, widgets em 5 tamanhos, calculadora, marcos/restauração, corpus e análises no IndexedDB, recarga, pacotes e fallback sem IndexedDB.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.close();});
