const {chromium,webkit}=require('playwright'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..'),out=process.env.QA_OUTPUT||'/tmp',engine=process.env.BROWSER_ENGINE||'chromium';fs.mkdirSync(out,{recursive:true});let browser;const errors=[];
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end(fs.readFileSync(path.join(root,'index.html')));});
async function form(p,trigger,name){if(trigger==='#original-new')await p.click('#desktop-organize');await p.click(trigger);await p.fill('#project-name',name);await p.click('#project-create');}
async function menu(p,trigger){await p.click('#os-start');await p.click('#start-system-toggle');await p.click(trigger);}
async function originalAction(p,id){if(await p.locator(id).isHidden())await p.click('#original-more');await p.click(id);}
async function shot(p,name){await p.screenshot({path:path.join(out,engine+'-'+name+'.png')});}
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
 browser=await(engine==='webkit'?webkit:chromium).launch({headless:true,args:engine==='chromium'?['--no-sandbox']:[]});
 const c=await browser.newContext({viewport:{width:1366,height:768},serviceWorkers:'block'}),p=await c.newPage();p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));
 await p.goto(url);await form(p,'#project-new','Conto');await p.click('#cabinet-new');await p.fill('#titulo','O cais');await p.fill('#manuscrito','As luzes do cais apagaram uma a uma.');await p.keyboard.press('Control+s');await p.click('#desk-minimize');
 assert.equal(await p.locator('.notebook-cover').count(),1);assert.equal(await p.locator('.original-box').count(),0);
 assert.equal(await p.locator('#original-new').isVisible(),false);await form(p,'#original-new','Livro do mar');assert.equal(await p.locator('#original-title-label').textContent(),'Livro do mar');
 await form(p,'#volume-new','Primeiro volume');await p.click('#cabinet-new');await p.fill('#titulo','A chegada');await p.fill('#manuscrito','A porta estava aberta.');await p.keyboard.press('Control+s');await p.click('#desk-minimize');
 await form(p,'#volume-new','Segundo volume');await p.click('#notebook-back');assert.equal(await p.locator('.notebook-cover').count(),2);assert.equal(await p.locator('#path-original').textContent(),'Livro do mar');
 await p.reload();assert.equal(await p.locator('#original-title-label').textContent(),'Livro do mar');assert.equal(await p.locator('.notebook-cover').count(),2);assert.equal(await p.locator('#notebook-area').getAttribute('data-drawer-open'),'true');await shot(p,'gaveta-aberta');
 const ev=p.waitForEvent('download');await originalAction(p,'#original-export');const packet=fs.readFileSync(await(await ev).path());const data=JSON.parse(packet);assert.equal(data.originals[0].name,'Livro do mar');assert.equal(data.notebooks.length,2);assert.equal(data.documents.length,1);
 await p.click('#original-back');assert.equal(await p.locator('.original-box').count(),1);assert.equal(await p.locator('.drawer-book-spine').count(),2);assert.equal(await p.locator('.notebook-cover').count(),1);await shot(p,'gavetas-1366');
 for(const [width,height]of [[320,568],[390,844],[667,375]]){await p.setViewportSize({width,height});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.getByRole('button',{name:'Abrir gaveta Livro do mar',exact:true}).click();const b=await p.locator('#original-back').boundingBox();assert.ok(b.x>=0&&b.x+b.width<=width+1);await p.click('#original-back');if(width===320){const boxes=await p.locator('.original-box').boundingBox(),area=await p.locator('#desktop-surface').boundingBox(),start=await p.locator('#project-new').boundingBox();assert.ok(start.y>=area.y&&boxes.y>=area.y&&boxes.y+boxes.height<=area.y+area.height,'gaveta inteira e criação visíveis em 320 px');for(const id of ['#project-new','#desktop-organize','#os-start']){const r=await p.locator(id).boundingBox();assert.ok(r.width>=44&&r.height>=44,id+' com alvo confortável');}await shot(p,'gavetas-320');}}
 await p.setViewportSize({width:1366,height:768});await p.getByRole('button',{name:'Abrir caderno Conto',exact:true}).click();await menu(p,'#start-settings');await p.selectOption('#notebook-parent',data.originals[0].id);await p.click('#notebook-parent-save');await p.click('#mesa-close');await p.click('#desk-minimize');assert.equal(await p.locator('.notebook-cover').count(),3);
 await originalAction(p,'#original-trash');await p.click('#app-dialog-accept');assert.equal(await p.locator('.original-box').count(),0);assert.equal(await p.locator('.notebook-cover').count(),0);
 await menu(p,'#start-trash');await p.getByRole('button',{name:'Restaurar gaveta completa'}).click();await p.click('#acervo-close');await p.getByRole('button',{name:'Abrir gaveta Livro do mar',exact:true}).click();assert.equal(await p.locator('.notebook-cover').count(),3);
 await p.click('#original-back');await menu(p,'#start-about');assert.equal(await p.locator('#welcome-reception').isVisible(),true);await shot(p,'recepcao');await p.setViewportSize({width:320,height:568});assert.equal(await p.locator('#welcome-reception').evaluate(n=>n.scrollWidth>n.clientWidth+1),false);await shot(p,'recepcao-320');await p.click('#window-close');
 const fresh=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),q=await fresh.newPage();q.setDefaultTimeout(12000);q.on('pageerror',e=>errors.push(e.message));await q.goto(url);await menu(q,'#start-settings');await q.setInputFiles('#import-file',{name:'obra.scrvrl',mimeType:'application/json',buffer:packet});await q.click('#app-dialog-accept');await q.getByRole('button',{name:'Abrir gaveta Livro do mar',exact:true}).click();assert.equal(await q.locator('.notebook-cover').count(),2);await q.getByRole('button',{name:'Abrir caderno Primeiro volume',exact:true}).click();assert.equal(await q.locator('#manuscrito').inputValue(),'A porta estava aberta.');
 // Failure must keep the editor and its unsaved text available.
 await q.evaluate(()=>{const old=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.indexOf('escrevaral.astra.v1.doc.')===0)throw new DOMException('quota','QuotaExceededError');return old.call(this,k,v);};});await q.fill('#manuscrito','Ainda não guardado.');await q.click('#path-projects');assert.equal(await q.locator('#manuscrito').isVisible(),true);assert.equal(await q.locator('#manuscrito').inputValue(),'Ainda não guardado.');
 assert.deepEqual(errors,[]);console.log('OK '+engine+': caderno direto; gaveta opcional; pilha visual; dois volumes; recarga; breadcrumbs; pacote; organização; lixeira/restauração; recepção; alvos e três viewports; importação e bloqueio de navegação sem gravação.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.close();});
