const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),path=require('path');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),ctx=vm.createContext({});
const scripts=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
for(const s of scripts){if(s.includes('root.Escr.mountUtilities'))break;vm.runInContext(s,ctx);}
const E=ctx.Escr,vault=E.createVault(E.knowledge),tr=E.createSignalTriage(E),cases=[];
function test(lens,text,count,kind){const result=vault.analyze(lens,text);assert.equal(result.findings.length,count,lens+': '+text);for(const f of result.findings){assert.equal(text.slice(f.start,f.end),f.snippet);assert.ok(f.evidence.source&&f.evidence.limit);if(kind)assert.equal(f.id,kind);for(const o of f.occurrences||[])assert.equal(E.reading.canonical(text.slice(o.start,o.end)),E.reading.canonical(f.snippet));}cases.push({lens,text,expected:count,signal:!!tr.scan(text).signals[lens],findings:result.findings.map(f=>({id:f.id,start:f.start,end:f.end,snippet:f.snippet}))});return result;}
test('expressoes','De vez em quando, volto.',1,'PTBR-EST-003');
test('expressoes','No final. Das contas, volto.',0);
test('expressoes','No\tfinal\u00a0das contas, volto.',1);
test('expressoes','Em u\u0301ltima ana\u0301lise, volto.',1);
test('expressoes','em ultima analise',0);
test('expressoes','no final das contasextras',0);
test('expressoes','no final\ndas contas',0);
test('expressoes','“de vez em quando”',0);
test('expressoes','“de vez em quando',0);
test('expressoes','`de vez em quando` e https://exemplo.com/de-vez-em-quando',0);
const dup=test('expressoes','No final das contas. No final das contas.',2);assert.notEqual(dup.findings[0].start,dup.findings[1].start);
test('repeticao','muito muito',1,'PTBR-REP-002');
test('repeticao','MUITO muito muito',1,'PTBR-REP-002');
test('repeticao','falou que falou',1,'PTBR-REP-003');
test('repeticao','falou que escreveu',0);
test('repeticao','muito, muito',0);
test('repeticao','casa azul casa verde casa',1,'PTBR-REP-001');
test('repeticao','casa “casa” casa',0);
test('repeticao','casa\n\ncasa',0);
test('repeticao','casa\ncasa',0);
test('repeticao','casa azul\ncasa verde casa',1,'PTBR-REP-001');
test('repeticao','casa. Casa',0);
test('repeticao','pode pôde',0);
test('repeticao','café cafe\u0301',1,'PTBR-REP-002');
test('repeticao','falou falaram fala',0);
test('repeticao','a a',0);
test('repeticao','22 22',0);
const filler=Array(38).fill('e').join(' ');test('repeticao','casa casa '+filler+' casa',1,'PTBR-REP-002');
const far=Array(45).fill('e').join(' ');test('repeticao','casa '+far+' casa '+far+' casa',0);
const repeated=Array.from({length:110},(_,i)=>'palavra'+String.fromCharCode(97+i%26)+String.fromCharCode(97+Math.floor(i/26))).map(w=>w+' '+w).join('\n\n');
const capped=vault.analyze('repeticao',repeated);assert.equal(capped.findings.length,100);assert.equal(capped.limited,true);
assert.equal(E.styleData.entries.length,1448);assert.equal(ctx.PTBR,undefined,'pacote completo não incorporado');
assert.ok(html.includes(fs.readFileSync(path.join(root,'ptbr/triagem.js'),'utf8')));
fs.writeFileSync(path.join(root,'ptbr/auditoria/matriz-lentes.json'),JSON.stringify({base:'9d167407962300d82393dee3262c3dbb32cc994f',cases},null,2)+'\n');
console.log('LENTES OK: '+cases.length+' casos reais, posições UTF-16, dupla ocorrência, limites, diacríticos, citações, código, autoria e catálogo existente + 1 expressão local.');
