// Teste de apresentação com o motor real e DOM simulado; não certifica geometria CSS.
const {Node,setup}=require('../ptbr/teste-painel.js');
const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),path=require('path');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),ctx=vm.createContext({});
for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){if(m[1].includes('root.Escr.mountUtilities'))break;vm.runInContext(m[1],ctx);}
const E=ctx.Escr,doc=new Node('document'),timers=[];
doc.createElement=tag=>new Node(tag);doc.createElementNS=(ns,tag)=>new Node(tag);
Node.prototype.getBoundingClientRect=function(){return{left:this.attrs['data-reading-index']*95||0,width:this.className==='ptbr-word-row'?1000:90};};
const listeners={},win={Escr:E,document:doc,setTimeout:fn=>{timers.push(fn);return timers.length;},clearTimeout:()=>{},addEventListener:(e,fn)=>listeners[e]=fn,removeEventListener:e=>delete listeners[e]};
vm.runInNewContext(fs.readFileSync(path.join(root,'ptbr/leitura-visual.js'),'utf8'),{window:win});
function all(n,cls){return(n.className===cls?[n]:[]).concat(...n.childNodes.map(c=>all(c,cls)));}
function tags(n,tag){return(n.tagName===tag?[n]:[]).concat(...n.childNodes.map(c=>tags(c,tag)));}
const source='🎼 Eu canto. O canto terminou. cafe\u0301 qwertyer.',f=E.createVault(E.knowledge).analyze('morfologia',source).findings,parent=new Node('div');
let current=true,picked=[];
const renderer=E.renderReadingMap(parent,{snapshot:source,lens:'morfologia',findings:f,isCurrent:()=>current,onSelect:(item,target)=>{picked.push(item);target.textContent=item.evidence.observation;}});
while(timers.length)timers.shift()();
const words=all(parent,'ptbr-word');assert.equal(words.length,f.length);
assert.ok(tags(parent,'path').length>0,'arcos apenas a partir de apoios do motor');
const cantos=words.filter(x=>x.textContent.startsWith('canto'));
assert.equal(cantos.length,2);cantos[0].click();assert.equal(picked.at(-1).feature,'verbo');cantos[1].click();assert.equal(picked.at(-1).feature,'substantivo');
assert.notEqual(picked.at(-1).start,picked.at(-2).start,'homógrafos mantêm posições distintas');
const unknown=words.find(x=>x.textContent.startsWith('qwertyer'));assert.ok(unknown.textContent.includes('sem leitura'));unknown.click();
while(timers.length)timers.shift()();assert.equal(tags(parent,'path').length,0,'sem arcos inventados para palavra desconhecida');
current=false;const before=picked.length;cantos[0].click();assert.equal(picked.length,before,'resultado obsoleto não reage');
renderer.destroy();assert.equal(listeners.resize,undefined,'remove listener ao trocar a lente');
current=true;cantos[0].click();assert.equal(picked.length,before,'renderer cancelado não reage');
const invalid=new Node('div');E.renderReadingMap(invalid,{snapshot:source,lens:'morfologia',findings:[{start:0,end:2,snippet:'errado'}],onSelect:()=>assert.fail('span inválido')});assert.equal(all(invalid,'ptbr-word').length,0);
const literal='<img src=x onerror=alert(1)>',safe=new Node('div');E.renderReadingMap(safe,{snapshot:literal,lens:'ortografia',findings:[{start:0,end:literal.length,snippet:literal}],onSelect:()=>{}});assert.equal(tags(safe,'img').length,0);assert.ok(safe.textContent.includes(literal));
assert.ok(html.includes(fs.readFileSync(path.join(root,'ptbr/leitura-visual.js'),'utf8')));assert.ok(html.includes(fs.readFileSync(path.join(root,'ptbr/leitura-visual.css'),'utf8')));
const syntaxText='A menina não leu a carta ontem. A menina canta.',syntaxFindings=E.createVault(E.knowledge).analyze('sintaxe',syntaxText).findings,syntaxParent=new Node('div');
current=true;picked=[];
const syntaxRenderer=E.renderReadingMap(syntaxParent,{snapshot:syntaxText,lens:'sintaxe',findings:syntaxFindings,isCurrent:()=>current,onSelect:f=>picked.push(f)});
while(timers.length)timers.shift()();
assert.equal(all(syntaxParent,'ptbr-reading-fragment').length,2);
assert.ok(syntaxParent.textContent.includes('Núcleo: menina'));
assert.ok(tags(syntaxParent,'path').length>0);
const termButtons=all(syntaxParent,'ptbr-syntax-term'),obj=termButtons.find(b=>b.attrs['aria-label'].startsWith('Objeto direto:'));
obj.click();while(timers.length)timers.shift()();assert.equal(picked.at(-1).snippet,'a carta');
assert.ok(all(syntaxParent,'ptbr-syntax-links')[0].textContent.includes('“leu” ↔ “a carta”'),'relação também disponível em texto');
assert.equal(tags(syntaxParent,'path').length,1,'somente vínculo selecionado');
const beforeSyntax=picked.length;current=false;obj.click();assert.equal(picked.length,beforeSyntax);syntaxRenderer.destroy();assert.equal(listeners.resize,undefined);
current=true;obj.click();assert.equal(picked.length,beforeSyntax);
// Se o autor dispensar um constituinte, não inventar seta para o nó ausente.
const partial=new Node('div'),remaining=syntaxFindings.filter(f=>f.feature!=='Núcleo verbal');
const partialRenderer=E.renderReadingMap(partial,{snapshot:syntaxText,lens:'sintaxe',findings:remaining,onSelect:()=>{}});
while(timers.length)timers.shift()();assert.equal(tags(partial,'path').length,0);partialRenderer.destroy();
const integrated=setup(syntaxText,[],E);integrated.panel.hidden=false;integrated.panel.focus();
assert.deepEqual(integrated.calls,[]);
integrated.wheel.childNodes.find(b=>b.attrs['data-ptbr-lens']==='sintaxe').click();integrated.flush();
assert.deepEqual(integrated.calls,['sintaxe']);assert.equal(all(integrated.board,'ptbr-reading-fragment').length,2);
all(integrated.board,'ptbr-syntax-term').find(b=>b.attrs['aria-label'].startsWith('Objeto direto:')).click();integrated.flush();
const visibleDetails=all(integrated.board,'ptbr-reading-details')[0];assert.ok(visibleDetails.textContent.includes('Objeto direto: uma leitura possível.'));
tags(visibleDetails,'button').find(b=>b.textContent==='Ver no texto').click();
assert.equal(integrated.manuscript.value.slice(integrated.manuscript.selectionStart,integrated.manuscript.selectionEnd),'a carta');assert.equal(integrated.manuscript.value,syntaxText);
integrated.manuscript.value='Outro texto.';integrated.manuscript.emit('input');integrated.flush();assert.equal(all(integrated.board,'ptbr-reading').length,0);assert.deepEqual(integrated.calls,['sintaxe']);
const locutionText='Eu estou lendo o livro.',locutionPanel=setup(locutionText,[],E);locutionPanel.panel.hidden=false;locutionPanel.panel.focus();
locutionPanel.wheel.childNodes.find(b=>b.attrs['data-ptbr-lens']==='sintaxe').click();locutionPanel.flush();
const locutionButton=all(locutionPanel.board,'ptbr-syntax-term').find(b=>b.attrs['aria-label'].startsWith('Locução verbal:'));
assert.ok(locutionButton.textContent.includes('Auxiliar: estou'));assert.ok(locutionButton.textContent.includes('Principal: lendo'));locutionButton.click();locutionPanel.flush();
const locutionDetails=all(locutionPanel.board,'ptbr-reading-details')[0];assert.ok(locutionDetails.textContent.includes('não são contadas como duas orações'));
tags(locutionDetails,'button').find(b=>b.textContent==='Ver no texto').click();assert.equal(locutionPanel.manuscript.value.slice(locutionPanel.manuscript.selectionStart,locutionPanel.manuscript.selectionEnd),'estou lendo');assert.equal(locutionPanel.manuscript.value,locutionText);
const relativeText='A menina que está cantando trabalha.',relativePanel=setup(relativeText,[],E);relativePanel.panel.hidden=false;relativePanel.panel.focus();
assert.deepEqual(relativePanel.calls,[]);
relativePanel.wheel.childNodes.find(b=>b.attrs['data-ptbr-lens']==='relativas').click();relativePanel.flush();
assert.deepEqual(relativePanel.calls,['relativas']);
const relativeDetails=all(relativePanel.board,'ptbr-reading-details')[0];
assert.ok(relativeDetails.textContent.includes('retoma “menina” e é sujeito de “está cantando”'));
assert.ok(relativeDetails.textContent.includes('que está cantando'));
tags(relativeDetails,'button').find(b=>b.textContent==='Ver no texto').click();
assert.equal(relativePanel.manuscript.value.slice(relativePanel.manuscript.selectionStart,relativePanel.manuscript.selectionEnd),'que está cantando');
assert.equal(relativePanel.manuscript.value,relativeText);
relativePanel.manuscript.value='A menina canta.';relativePanel.manuscript.emit('input');relativePanel.flush();
assert.equal(all(relativePanel.board,'ptbr-reading').length,0);assert.deepEqual(relativePanel.calls,['relativas']);
console.log('VISUAL OK: motor real, relativa/antecedente, ocorrência selecionada, apoios, desconhecimento, spans, texto literal, invalidação e descarte. Geometria pendente de navegador.');
