// Teste de integração; Playwright é ferramenta de QA e não integra o aplicativo.
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.join(__dirname,'..'),out=process.env.QA_OUTPUT||'/tmp';
const server=http.createServer((req,res)=>{const file=path.join(root,req.url==='/'?'index.html':req.url.split('?')[0]);if(!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':'text/html');res.end(fs.readFileSync(file));});
let browser;const errors=[];
async function create(p,name){await p.click('#project-new');await p.fill('#project-name',name);await p.click('#project-create');}
async function write(p,title,body){await p.click('#cabinet-new');await p.fill('#titulo',title);await p.fill('#manuscrito',body);await p.click('#desk-minimize');}
async function universe(p){await p.click('#os-start');await p.click('#start-universe');}
async function record(p,button,name,description){await p.click('#story-records');await p.getByRole('button',{name:button,exact:true}).click();await p.fill('#story-field-name',name);await p.fill('#story-field-description',description);await p.locator('#story-form button[type=submit]').click();}
async function scene(p,title){await p.click('#story-events');await p.getByRole('button',{name:'+ Nova cena',exact:true}).click();await p.fill('#story-field-title',title);await p.fill('#story-field-summary','Ana chega ao porto depois da tempestade.');await p.fill('#story-field-when','Ato I · Dia 1');await p.selectOption('#story-field-chapter',{label:'O silêncio das velas'});await p.locator('input[name=characters]').check();await p.locator('input[name=settings]').check();await p.locator('#story-form button[type=submit]').click();}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/tmp/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:1440,height:900},hasTouch:true,serviceWorkers:'block'});const p=await context.newPage();p.setDefaultTimeout(8000);p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto('http://127.0.0.1:'+server.address().port);
assert.equal(await p.locator('#calculator-keys button').count(),21);
await create(p,'Marés');await write(p,'O silêncio das velas','Ana deixou o casaco sobre a cadeira.\n\n— Você voltou.\n\nO vento carregava areia.');await p.getByRole('button',{name:'Abrir caderno Marés',exact:true}).click();await p.click('#back-cabinet');await write(p,'Depois da tempestade','O cais estava vazio.');await p.getByRole('button',{name:'Abrir caderno Marés',exact:true}).click();await universe(p);assert.equal(await p.locator('.polaroid').count(),2);
await record(p,'+ Personagem','Ana','Navegante. Reconhece o cais pelo cheiro.');await record(p,'+ Cenário','Porto','Uma cidade atravessada pelo vento.');await scene(p,'O retorno');await p.screenshot({path:path.join(out,'universo-acontecimentos.png')});await p.click('#story-chapters');assert.ok((await p.locator('.polaroid').first().textContent()).includes('Ana'));assert.ok((await p.locator('.polaroid').first().textContent()).includes('Porto'));await p.screenshot({path:path.join(out,'universo-capitulos.png')});
await p.locator('.polaroid').last().getByRole('button',{name:'Mover para antes',exact:true}).click();assert.ok((await p.locator('.polaroid h3').first().textContent()).includes('Depois da tempestade'));await p.locator('.polaroid').last().locator('.story-open').click();assert.equal(await p.locator('#titulo').inputValue(),'O silêncio das velas');await p.fill('#titulo','Velas apagadas');await p.fill('#manuscrito','Ana voltou.');await universe(p);assert.equal(await p.locator('.polaroid h3').last().textContent(),'Velas apagadas');assert.ok((await p.locator('.polaroid').last().textContent()).includes('2 palavras'));await p.click('#story-events');assert.ok((await p.locator('.polaroid').textContent()).includes('Velas apagadas'));
// Renomear mantém vínculos; excluir personagem retira referências sem alterar texto.
await p.click('#story-records');await p.locator('.polaroid').first().getByRole('button',{name:'Editar ficha'}).click();await p.fill('#story-field-name','Ana do mar');await p.locator('#story-form button[type=submit]').click();await p.click('#story-chapters');assert.ok((await p.locator('.polaroid').last().textContent()).includes('Ana do mar'));
// Formulário sobrevive à falta de espaço.
await p.click('#story-records');await p.getByRole('button',{name:'+ Personagem',exact:true}).click();await p.fill('#story-field-name','Bruno');await p.evaluate(()=>{window.originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='escrevaral.astra.notebooks.v1')throw new Error('Sem espaço');return window.originalSet.call(this,k,v);};});await p.locator('#story-form button[type=submit]').click();assert.equal(await p.locator('#story-editor').isVisible(),true);assert.equal(await p.locator('#story-field-name').inputValue(),'Bruno');await p.evaluate(()=>{Storage.prototype.setItem=window.originalSet;});await p.locator('#story-form button[type=submit]').click();assert.equal(await p.locator('#story-editor').isVisible(),false);
await p.click('#story-close');await p.click('#screen-lock');const original=await p.locator('#manuscrito').inputValue();await p.fill('#lock-password','segredo-imaginario');await p.locator('#lock-form button').click();assert.equal(await p.locator('#lock-curtain').isVisible(),true);await p.keyboard.press('Escape');await p.keyboard.press('Control+k');assert.equal(await p.locator('#lock-curtain').isVisible(),true);assert.equal(await p.locator('#manuscrito').inputValue(),original);assert.equal(await p.evaluate(()=>Object.keys(localStorage).some(k=>(localStorage.getItem(k)||'').includes('segredo-imaginario'))),false);await p.screenshot({path:path.join(out,'cadeado.png')});await p.reload();assert.equal(await p.locator('#lock-curtain').isVisible(),true);await p.locator('#keychain-ring').focus();await p.keyboard.press('Enter');assert.equal(await p.locator('#lock-curtain').isVisible(),false);
// Pacote real, inclusive cópia com remapeamento de capítulo.
await p.click('#back-cabinet');let ev=p.waitForEvent('download');await p.click('#notebook-export');let packet=JSON.parse(fs.readFileSync(await (await ev).path(),'utf8'));assert.equal(packet.notebooks[0].data.story.scenes.length,1);await p.click('#os-start');await p.click('#start-settings');await p.setInputFiles('#import-file',{name:'mares.scrvrl',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(packet))});await p.waitForFunction(()=>document.querySelectorAll('.notebook-cover').length===2);if(await p.locator('#mesa-close').isVisible())await p.click('#mesa-close');await p.getByRole('button',{name:'Abrir caderno Marés — cópia 1',exact:true}).click();await universe(p);assert.ok((await p.locator('.polaroid').last().textContent()).includes('Ana do mar'));await p.click('#story-events');assert.ok((await p.locator('.polaroid').textContent()).includes('Velas apagadas'));await p.click('#story-close');await p.click(await p.locator('#desk-minimize').isVisible()?'#desk-minimize':'#window-minimize');await create(p,'Outro mundo');await universe(p);await p.click('#story-records');assert.equal(await p.locator('.polaroid').count(),0);await p.click('#story-close');await p.click('#window-minimize');await p.getByRole('button',{name:'Abrir caderno Marés',exact:true}).click();
for(const [w,h] of [[820,1180],[390,844],[320,568],[667,375]]){await p.setViewportSize({width:w,height:h});await universe(p);await p.click('#story-events');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await p.evaluate(()=>document.getElementById('story-screen').scrollWidth>innerWidth),false);await p.screenshot({path:path.join(out,'universo-'+w+'.png')});await p.click('#story-close');await p.click('#screen-lock');await p.locator('#keychain-ring').tap();}
await p.setViewportSize({width:1440,height:900});await p.click('#os-start');await p.click('#start-settings');await p.click('#theme-dark');await p.click('#mesa-close');await universe(p);await p.screenshot({path:path.join(out,'universo-escuro.png')});assert.deepEqual(errors,[]);console.log('OK: capítulos, ordem, fichas, cenas, renomeação, atualização de palavras, quota, cadeado, recarga, teclado, exportação/importação com cópia, isolamento, 4 tamanhos e tema escuro.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.close();});
