/* Dados de personagens/cenas: vínculos, cópia e importação transacional. */
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync(require('path').join(__dirname,'../index.html'),'utf8'),scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(x=>x[1]),ctx=vm.createContext({});
for(const marker of ["var prefix = 'escrevaral.astra.v1.doc.'",'E.validPlanner =','/* Universo do caderno:','/* Cadernos: dados ES5'])vm.runInContext(scripts.find(s=>s.includes(marker)),ctx);
const E=ctx.Escr;
class Storage{constructor(){this.data=new Map();}get length(){return this.data.size;}key(i){return [...this.data.keys()][i];}getItem(k){return this.data.get(k)||null;}setItem(k,v){this.data.set(k,String(v));}removeItem(k){this.data.delete(k);}}
const storage=new Storage(),books=E.createNotebooks(storage),archive=E.createArchive(storage),b=books.add('Marés'),second=books.add('Outro');let d=E.freshDocument();d.projectId=b.id;d.project=b.name;d.title='A chegada';d.text='Ana voltou ao porto.';d=archive.save(d).document;
const s=E.story.empty();s.characters.push({id:'person-ana',name:'Ana',description:'Navegante'});s.settings.push({id:'place-porto',name:'Porto',description:''});s.scenes.push({id:'scene-chegada',title:'A chegada',summary:'Barco atraca',when:'Dia 1',chapter:d.noteId,characters:['person-ana'],settings:['place-porto']});s.chapters.push({noteId:d.noteId,characters:['person-ana'],settings:[]});assert.ok(E.story.valid(s));books.update(b.id,{data:{story:s,planner:{},attachments:[{name:'mapa',text:'referência'}]}});
const packet=books.pack(archive.list(true).documents,b.id);books.validate(packet);assert.equal(packet.notebooks.length,1);assert.equal(books.pack(archive.list(true).documents,second.id).notebooks[0].data.story,undefined);
const target=new Storage(),other=E.createNotebooks(target);other.bring(packet);other.bring(packet);const copied=other.list().find(x=>x.id!==b.id);const copiedDoc=E.createArchive(target).list().documents.find(x=>x.projectId===copied.id);assert.equal(copied.data.story.scenes[0].chapter,copiedDoc.noteId);assert.equal(copied.data.story.chapters[0].noteId,copiedDoc.noteId);assert.notEqual(copiedDoc.noteId,d.noteId);assert.deepEqual(JSON.parse(JSON.stringify(other.get(b.id).data.story)),JSON.parse(JSON.stringify(s)));
const removed=E.story.remove(s,'characters','person-ana');assert.ok(E.story.valid(removed));assert.equal(removed.scenes[0].characters.length,0);assert.equal(removed.chapters[0].characters.length,0);assert.equal(s.characters.length,1);assert.equal(E.story.members(s,d.noteId,'characters').length,1);
const bad=JSON.parse(JSON.stringify(packet));bad.notebooks[0].data.story.scenes[0].characters=['unknown'];const before=JSON.stringify([...target.data]);assert.throws(()=>other.bring(bad));assert.equal(JSON.stringify([...target.data]),before);
const renamed=E.story.read(books.get(b.id).data);renamed.characters[0].name='Ana do mar';books.update(b.id,{data:{...books.get(b.id).data,story:renamed}});assert.equal(E.story.members(renamed,d.noteId,'characters')[0].name,'Ana do mar');assert.equal(archive.get(d.id).text,'Ana voltou ao porto.');
console.log('OK: fichas, vínculos, isolamento, dados existentes, exportação, cópia com remapeamento, exclusão sem perda de texto e rejeição transacional de vínculos inválidos.');
